### ISSUE TITLE
Feature request: python3 support

### ISSUE THREAD

**Issue by fsacer** [dirkjanm/krbrelayx#11]

**Comment by dirkjanm** [comment]
Not a 100% sure but I thought the tools were already compatible with python 3. Unless you're getting specific errors while running it?

**Comment by fsacer** [comment]
For example line 222 in kerbrelayx.py fails because of print "".

**Comment by dirkjanm** [comment]
Hmmm ok I will have a look at this, thanks!

**Comment by edermi** [comment]
Same for printerbug.py. Line 78 and 92 need `except Exception as e`

**Comment by dirkjanm** [comment]
Should work with py3 now, let me know if you run into issues. I did some limited testing but probably not all.
