### ISSUE TITLE
addspn.py doesn't handle useraccounts with '.' in the name.

### ISSUE THREAD

**Issue by micahvandeusen** [dirkjanm/krbrelayx#18]
I was getting the following error when trying to do anything with a target user with a . character in the name.
[!] Target record not found!

This is do to the check on line
https://github.com/dirkjanm/krbrelayx/blob/d6a273843b8a67f39b5e7e9367eef4ebc2f2661c/addspn.py#L92

**Comment by mayomacam** [comment]
well i update to script according to my use on that place if i have user with . in it... i can update script on place so that it treat that as user..
`if '.' in targetuser:
        search = '(SAMAccountName=%s)' % targetuser`
well for me it works.
