### ISSUE TITLE
AttributeError: 'Resolver' object has no attribute 'resolve'

### ISSUE THREAD

**Issue by akashJx** [dirkjanm/krbrelayx#23]
### Help!
I have all the dependencies installed. But it is not working as expected. 
I am getting the following error

```
dnstool.py -u intelligence\\Tiffany.Molina -p SOMEPASSWORD --action add --record web-kali --data 10.10.17.81 --type A intelligence.htb

[-] Connecting to host...
[-] Binding to host
[+] Bind OK
Traceback (most recent call last):
  File "dnstool.py", line 543, in <module>
    main()
  File "dnstool.py", line 465, in main
    record = new_record(addtype, get_next_serial(args.host, zone,args.tcp))
  File "dnstool.py", line 242, in get_next_serial
    res = dnsresolver.resolve(zone, 'SOA',tcp=tcp)
AttributeError: 'Resolver' object has no attribute 'resolve'
```

**Comment by dirkjanm** [comment]
hey, there is a slightly newer version of dnspython, which doesn't have this issue. Also it's probably better to remove the credentials from your examples and screenshots, they may contain spoilers for others.

**Comment by akashJx** [comment]
Spoiler removed. There might be some python version conflict. 
It's a funny situation it works on other people's systems but it is not working on my system. 😅
I will try other ways. Thanks.
