### ISSUE TITLE
AttributeError: 'GenericRdata' object has no attribute 'key'

### ISSUE THREAD

**Issue by wqreytuk** [dirkjanm/krbrelayx#24]
I'm using python3 to run the latested mitm6 and krbrelayx, ad cs attack through dns kerberos relay
works fine on ubuntu
but got this error on [kali](https://www.kali.org/get-kali/#kali-virtual-machines) and [kylinos](https://www.kylinos.cn/scheme/desktop/2.html)

![image](https://user-images.githubusercontent.com/48377190/158321665-53d34e63-e1af-4db2-9213-4cbce8711dbb.png)

**Comment by wqreytuk** [comment]
I don't if the information is enough to you to debug this issue, if you need more information, just ask

**Comment by wqreytuk** [comment]
I've dumped the hex value of [dnsp](https://github.com/dirkjanm/krbrelayx/blob/master/lib/servers/dnsrelayserver.py#L42)
![image](https://user-images.githubusercontent.com/48377190/158323420-05a5a6cc-9130-4a66-b831-b5ac4a4e4575.png)
and I [use this value to run the code](https://144.one/s/AdHji), it works fine and there is no exception is raised
![image](https://user-images.githubusercontent.com/48377190/158323566-253654ce-52e7-43bf-b162-47a64497f815.png)

**Comment by wqreytuk** [comment]
I can not figure out what is the real cause to this issue

**Comment by wqreytuk** [comment]
just tested, it will aslo raise this exception if I just [run this code](https://144.one/s/content.html?AdHji) on kali:
![image](https://user-images.githubusercontent.com/48377190/158329936-9fa3bb6d-64be-4760-a0bd-8e2c4fe72137.png)

**Comment by dirkjanm** [comment]
can you try updating your version of dnspython

**Comment by wqreytuk** [comment]
> can you try updating your version of dnspython

problem solved, thanks!
