### ISSUE TITLE
AttributeError: 'KrbRelayxConfig' object has no attribute 'setIsADCSAttack'

### ISSUE THREAD

**Issue by dtuncle** [dirkjanm/krbrelayx#25]
![image](https://user-images.githubusercontent.com/34520816/159972044-aaeaeb89-76e4-4bd9-a9d6-4cf6b742638c.png)

I found that the config.py file does not have the setIsADCSAttack method

Is it a problem with my environment here?

Thanks

**Comment by dirkjanm** [comment]
Can you try to install the latest impacket from git? Might fix the issue

**Comment by dtuncle** [comment]
I updated impacket, krbrelayx without any problem. But mitm6 prompts KeyError: 'mpl_toolkits.legacy_colorbar'. It tells me to install matplotlib 3.3.4, but I check it is this version
![image](https://user-images.githubusercontent.com/34520816/160039249-700d174e-4823-4123-8ff2-c21f67d695cd.png)
![image](https://user-images.githubusercontent.com/34520816/160039367-118dcc37-53cc-404d-9af1-e059d311b159.png)

Update impacket to the latest version
![image](https://user-images.githubusercontent.com/34520816/160039534-f346199b-c70a-4d02-a1b9-63efa417f3e7.png)

python3.9.10

**Comment by dtuncle** [comment]
I updated impacket, krbrelayx without any problem. But mitm6 prompts KeyError: 'mpl_toolkits.legacy_colorbar'. It tells me to install matplotlib 3.3.4, but I check it is this version
![image](https://user-images.githubusercontent.com/34520816/160039249-700d174e-4823-4123-8ff2-c21f67d695cd.png)
![image](https://user-images.githubusercontent.com/34520816/160039367-118dcc37-53cc-404d-9af1-e059d311b159.png)

Update impacket to the latest version
![image](https://user-images.githubusercontent.com/34520816/160039534-f346199b-c70a-4d02-a1b9-63efa417f3e7.png)

python3.9.10
