### ISSUE TITLE
dnstool error

### ISSUE THREAD

**Issue by Lexus89** [dirkjanm/krbrelayx#3]
While i do succeed in creating new records with powermad i am getting the following error with dnstool:

LDAP operation failed. Message returned from server: constraintViolation 000020B5: AtrErr: DSID-03152B47, #1: 0: 000020B5: DSID-03152B47, problem 1005 (CONSTRAINT_ATT_TYPE), data 0, Att 9030e (objectCategory)

Is there a difference on how the records are set or PEBKAC?

**Comment by dirkjanm** [comment]
Are you running this in a subdomain by any chance?

**Comment by Lexus89** [comment]
Yes, indeed a subdomain

**Comment by dirkjanm** [comment]
Let me know if the latest version fixes it :)
