### ISSUE TITLE
Unsupported MechType 'NTLMSSP - Microsoft NTLM Security Support Provider

### ISSUE THREAD

**Issue by Cyb3rGh0st786** [dirkjanm/krbrelayx#34]
Hello Dirk, 

I get the "Unsupported MechType 'NTLMSSP - Microsoft NTLM Security Support Provider" in the last step when I try to authenticate with printer-bug and DFSCoerce. I could not find what the issue was. I have followed the below steps. 

1. DC - 2016 
2. Attacker- Kali 
3. Unconstrained delegation machine- Windows 10 

**Step - 1**
I got the AES-256 and 128 as well as NTHash of the machine account by running secretsdump.py 

**Step - 2**
Queried for the SPN 

![image](https://github.com/dirkjanm/krbrelayx/assets/7692857/5ed8e974-c6aa-4478-9777-8753166de76d)

**Step - 3**
Added SPN record 
![image](https://github.com/dirkjanm/krbrelayx/assets/7692857/bb7f61a0-c68f-413f-992d-c945733abd19)

**Step - 4** 
Added DNS record
![image](https://github.com/dirkjanm/krbrelayx/assets/7692857/53ad6e65-1c77-483e-a8f0-00432d601359)

**Step-5**
A record 
![image](https://github.com/dirkjanm/krbrelayx/assets/7692857/7fd692c8-8729-408f-81a1-8deb4196093b)

**Step- 6** 
nslookup verification 
![image](https://github.com/dirkjanm/krbrelayx/assets/7692857/3b210a84-c206-4c3a-9d9c-a814e8695592)

**Step - 7** 
Printer Bug 

![image](https://github.com/dirkjanm/krbrelayx/assets/7692857/8b047e58-93eb-4103-9202-2d6b6ea86a29)

DFSCoerce 
![image](https://github.com/dirkjanm/krbrelayx/assets/7692857/1255f5b5-c9ce-4ce7-8ec8-0548e01d004a)

**Step - 8**
Krbrelayx setup 

![image](https://github.com/dirkjanm/krbrelayx/assets/7692857/6471a4a0-f161-4b13-94ad-2883d452c02a)

Ultimately, I got the 'NTLMSSP - Microsoft NTLM Security Support Provider' error. 

I could not find figure out what the issue is

**Comment by kaleemshaik7867** [comment]
@dirkjanm , I have also set up the SPN. Could not figure out what the issue is 

![image](https://github.com/dirkjanm/krbrelayx/assets/7692857/0b62b808-f8a1-4956-a230-5f8c3823bbac)

**Comment by dirkjanm** [comment]
You appear to be coercing the connection based on an IP address instead of a hostname. If you use an IP address, the server will not initiate Kerberos but only use NTLM authentication as Kerberos requires a hostname.

**Comment by kaleemshaik7867** [comment]
Hello @dirkjanm, Thank you for the reply. When I use the hostname, I don't get any call back on the krbrelayx.py script. I only get it when I use the IP address. Also, I set up the DNS entry and here is the screenshot. 

![image](https://github.com/dirkjanm/krbrelayx/assets/7692857/143a14a9-c778-41f6-938c-0950617d0847)

Please help with what the issue could be.

**Comment by dirkjanm** [comment]
I don't know if this is a local lab, but this issue indicates that the server you are talking to might not be using the DNS server you added the record on, or you did not add the DNS record correctly. Note that in step 4 you appear to be using an SPN format and not an FQDN format for the DNS record. Also in step 5 you seem to remove the same record again?

**Comment by kaleemshaik7867** [comment]
Thank you so much and I will verify the same.
