### ISSUE TITLE
Crash on Cyrillic domain

### ISSUE THREAD

**Issue by kernelzeroday** [dirkjanm/krbrelayx#9]
I got the following error when attempting a login with printerbug.py on a Cyrillic domain, is it possible this is related to this issue or am I completely wrong here? New to the Impacket library so forgive me if this is off base. 

Issue in question: https://github.com/SecureAuthCorp/impacket/issues/51

Output:

# python printerbug.py DOMAIN\user:password@machine.domain.local attacker 
[*] Impacket v0.9.20-dev - Copyright 2019 SecureAuth Corporation
[*] Attempting to trigger authentication via rprn RPC at machine.domain.local
[-] SMB SessionError: STATUS_OBJECT_NAME_NOT_FOUND(The object name is not found.)
Traceback (most recent call last):
  File "printerbug.py", line 198, in <module>
    main()
  File "printerbug.py", line 191, in main
    lookup.dump(remote_name)
  File "printerbug.py", line 77, in dump
    self.lookup(rpctransport, remote_host)
  File "printerbug.py", line 87, in lookup
    dce.connect()
  File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/rpcrt.py", line 800, in connect
    return self._transport.connect()
  File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/transport.py", line 400, in connect
    self.__handle = self.__smb_connection.openFile(self.__tid, self.__filename)
  File "/usr/local/lib/python2.7/dist-packages/impacket/smbconnection.py", line 547, in openFile
    raise SessionError(e.get_error_code(), e.get_error_packet())
impacket.smbconnection.SessionError: SMB SessionError: STATUS_OBJECT_NAME_NOT_FOUND(The object name is not found.)

**Comment by dirkjanm** [comment]
Does the hostname include cryllic characters? Try specifying the IP instead, maybe that helps. If not I'm not sure it's related to the character set.

**Comment by airhack87** [comment]
Weird, I am getting the same error
"STATUS_OBJECT_NAME_NOT_FOUND"
Tried using the IP address also and it failed with the same error.
Domain and DC name does not contain anything special just a "-" in the dc name.

Any other pointers ?

**Comment by Yoga7xm** [comment]
I encountered the same problem and used both IP and hostname but reported the same error ...
SMB SessionError: STATUS_OBJECT_NAME_NOT_FOUND(The object name is not found.)

**Comment by Yoga7xm** [comment]
> Weird, I am getting the same error
> "STATUS_OBJECT_NAME_NOT_FOUND"
> Tried using the IP address also and it failed with the same error.
> Domain and DC name does not contain anything special just a "-" in the dc name.
> 
> Any other pointers ?

how do you resolve it? Can you help me....Thanks

**Comment by dirkjanm** [comment]
Which OS version are you running it against?

**Comment by XiaOkuoAi** [comment]
Have you solved the problem? I have encountered this problem。

**Comment by dirkjanm** [comment]
This is likely either an older OS version or a host that doesn't have the spool service started and thus doesn't expose the spool service via RPC.

**Comment by XiaOkuoAi** [comment]
> 这可能是较旧的OS版本或未启动后台打印服务的主机，因此未通过RPC公开后台打印服务。

My exchange is the server of 2012, and the printer service is enabled

**Comment by dirkjanm** [comment]
I don't have server 2012 to test. I only have 2012R2, which gives no error. Server 2008 does not have the spooler service exposed via RPC, and it gives "STATUS_OBJECT_NAME_NOT_FOUND". When I stop the printer spooler on 2012R2 it also gives the "STATUS_OBJECT_NAME_NOT_FOUND".
You could also try alternative implementations such as this [the original by lee here](https://github.com/leechristensen/SpoolSample/), but I think they will give the same error.
